#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace transport
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Transport")]
	public partial class TransportDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRuch(Ruch instance);
    partial void UpdateRuch(Ruch instance);
    partial void DeleteRuch(Ruch instance);
    #endregion
		
		public TransportDataClassesDataContext() : 
				base(global::transport.Properties.Settings.Default.TransportConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public TransportDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TransportDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TransportDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TransportDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ruch> Ruches
		{
			get
			{
				return this.GetTable<Ruch>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ruch")]
	public partial class Ruch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _nr_przystanku;
		
		private int _wsiadlo;
		
		private int _wysiadlo;
		
		private int _stan_po;
		
		private System.DateTime _czas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onnr_przystankuChanging(int value);
    partial void Onnr_przystankuChanged();
    partial void OnwsiadloChanging(int value);
    partial void OnwsiadloChanged();
    partial void OnwysiadloChanging(int value);
    partial void OnwysiadloChanged();
    partial void Onstan_poChanging(int value);
    partial void Onstan_poChanged();
    partial void OnczasChanging(System.DateTime value);
    partial void OnczasChanged();
    #endregion
		
		public Ruch()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_przystanku", DbType="Int NOT NULL")]
		public int nr_przystanku
		{
			get
			{
				return this._nr_przystanku;
			}
			set
			{
				if ((this._nr_przystanku != value))
				{
					this.Onnr_przystankuChanging(value);
					this.SendPropertyChanging();
					this._nr_przystanku = value;
					this.SendPropertyChanged("nr_przystanku");
					this.Onnr_przystankuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wsiadlo", DbType="Int NOT NULL")]
		public int wsiadlo
		{
			get
			{
				return this._wsiadlo;
			}
			set
			{
				if ((this._wsiadlo != value))
				{
					this.OnwsiadloChanging(value);
					this.SendPropertyChanging();
					this._wsiadlo = value;
					this.SendPropertyChanged("wsiadlo");
					this.OnwsiadloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wysiadlo", DbType="Int NOT NULL")]
		public int wysiadlo
		{
			get
			{
				return this._wysiadlo;
			}
			set
			{
				if ((this._wysiadlo != value))
				{
					this.OnwysiadloChanging(value);
					this.SendPropertyChanging();
					this._wysiadlo = value;
					this.SendPropertyChanged("wysiadlo");
					this.OnwysiadloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stan_po", DbType="Int NOT NULL")]
		public int stan_po
		{
			get
			{
				return this._stan_po;
			}
			set
			{
				if ((this._stan_po != value))
				{
					this.Onstan_poChanging(value);
					this.SendPropertyChanging();
					this._stan_po = value;
					this.SendPropertyChanged("stan_po");
					this.Onstan_poChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_czas", DbType="DateTime NOT NULL")]
		public System.DateTime czas
		{
			get
			{
				return this._czas;
			}
			set
			{
				if ((this._czas != value))
				{
					this.OnczasChanging(value);
					this.SendPropertyChanging();
					this._czas = value;
					this.SendPropertyChanged("czas");
					this.OnczasChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
